### PR TITLE
Added padding declaration to UL to fix menu alignment

### PR DESCRIPTION
**Pull request by misterjonscott**
:hamburger:

### CODE REVIEW

**Comment by misterjonscott** [comment]
# Changes
I added a padding declaration to remove padding from the UL element in the topmenu.  The styles are a bit scattered, right now, so I would like to dive deeper into that, soon, but this is a solution for the ticket at hand.

# Testing
You'll need to have multiple companies on your account, and reference [this ticket](https://directemployersfoundation.atlassian.net/browse/PD-2102) to see the previous error versus this fix.

**Comment by tdphillips** [comment]
custom.css appears to only be used by base-react.html. How does this look on non-react pages?

**Comment by misterjonscott** [comment]
Fortunately, @tdphillips , the problem only appears on the Users page, which is the only page that seems to be using base-react template right now.  This will only affect that page.

**Comment by aspidites** [comment]
Begs the question if User Mangement is the only one using bsae-react, then why do we even have base-react?

**Comment by aspidites** [comment]
We need to version this file so that changes are picked up downstream. Eg. rename it "custom.173-2.css"

**Comment by misterjonscott** [comment]
My latest understanding was that all 3 new React apps were to use base-react, but that is not currently the case.  If this style, or that template, were adopted later, this style would, at worst, override a 0 padding, and, at best, fix future problems.  That said, our styles do need to be combined and cleaned up.  Hoping to get to that, soon.

**Comment by misterjonscott** [comment]
@aspidites I've added a wrapper to has the filenames, as that's the new process.  Thanks for pointing this out!

**Comment by aspidites** [comment]
Even better.

**Comment by lemniscate613** [comment]
:+1: 

`base-react.html` could be renamed to something like `base-bootstrap3.html` as that's why it exists. The plan is to have all new projects (e.g. all of the React apps) using Bootstrap 3.

**Comment by aspidites** [comment]
Tests are failing because compress isn't loaded in this template. [Here's](https://github.com/DirectEmployers/MyJobs/blob/quality-control/templates/redirect/base.html#L3) an example.

**Pull request merged**
