### PR TITLE
Make back button work from job detail view [PD-322]

### PR DESCRIPTION
**Pull request by tdphillips**
The easiest way to test:

* Point to staging database and solr
* Override your chosen domain in /etc/hosts
* Do a search and click more a bunch
* View a job
* Click back
* ???
* Profit (Also you should have a bunch of jobs loaded instead of only the default number)

### CODE REVIEW

**Comment by tdphillips** [comment]
Feel free to rip this apart. Browsers that lack history.replaceState are no longer supported.

**Comment by tdphillips** [comment]
Someone who is better at seo than I should take a look at what I did. I saw no way of resolving my ticket without discarding a bit of code and I'm not sure if that's acceptable.

**Comment by aspidites** [comment]
Results are re-ordered on back. Before viewing a job:
2015-04-01-124934_1916x1056_scrot
After clicking back:
2015-04-01-124957_1916x1056_scrot

**Comment by almathew** [comment]
We use the default ordering unless you specifically order by date. That shouldn't change.

**Comment by aspidites** [comment]
@almathew  I didn't specify anything. I simply clicked the back button. Did no sorting at all.

**Comment by tdphillips** [comment]
Destroying all of my work.

**Pull request closed without merging**
