### PR TITLE
Invitation user experience [PD-847]

### PR DESCRIPTION
**Pull request by tdphillips**
invitation

All tests pass.

### CODE REVIEW

**Comment by aspidites** [comment]
Do we have to worry about invitations on microsites?

**Comment by tdphillips** [comment]
What about them, specifically?

**Comment by aspidites** [comment]
I was originally curious as to whether Company Name should appear in the signature some where, but perhaps that's redundant. 

Would highlighting the company name be an improvement or detraction? Something like this:
http://jsfiddle.net/yz4c16fa/

Also, does it make sense to use the inviting company rather than the inviting user? ("My.jobs on behalf of Company Name")

**Comment by tdphillips** [comment]
Would that be a functional anchor or just a highlight?

Regarding inviting company vs. inviting user, this is the copy that I was provided with.

**Comment by aspidites** [comment]
Functional if we have access to the company url, otherwise just a highlight (though in that case, I'm sure there are better ways to do so).

**Comment by fezick** [comment]
The vast majority of invites will be for member tools on my.jobs. Lets deal with mircosite specific functionality when we get to it.

**Comment by fezick** [comment]
The email looks good to me.

**Comment by tdphillips** [comment]
@fezick I should mention that this doesn't contain the proposed subject change  that AJ asked for. I wasn't sure how desired that was.

**Comment by fezick** [comment]
Right now it says invitation, which is generic enough for me.

**Pull request merged**
