### PR TITLE
Pd 3566 commm action button feature branch

### PR DESCRIPTION
**Pull request by aljordan82**
## What's this PR do?
Add a common action button in PRM/NUO/PA , TJD, and Manage Users.
## How should this be manually tested?
* PRM, without selecting a partner, click the "Add Record" action button. The "Edit Record" form should appear with only the Partner field. select a partner and the rest of the form should appear.
* PRM, Select a partner, then click the "Add Record" button. All fields should be visible with the Partner preselected.
* PRM, the "New Record" button functionality shouldn't be affected.
* TJD, the action button should direct to "New organization"
* Manage user, the action button should direct to "Add User"

### Front-End

- [ ] Works on IE 11 and Edge
- [ ] Works on Mobile
- [ ] Unit tests added or ticket exists to add tests

### Separation of Concerns

- [ ] Back end "business logic" is implemented in plain python, Django model classes, and Django forms. (not Django views or other frameworks)
- [ ] Concerns of UI, api, and model are in separate code units.

### Tests

- [ ] Base classes used for python tests don't do too much unnecessary work.

### Migrations

- [ ] Migrations can be reversed.
- [ ] Current production code would continue to work after this migration is applied.
- [ ] Data migrations' forward/reverse functions should be decorated with `@only_on_default`.

### CODE REVIEW

**Comment by koonsies** [comment]
I'll start testing over this branch. Won't be overly exhaustive on the code, since we reviewed as we merged.

**Comment by koonsies** [comment]
Code looks sound. I'll review this after I finish the common-action PR

**Comment by koonsies** [comment]
I'm getting a strange error, I'd like someone else to verify that it exists..

**Comment by aljordan82** [comment]
@koonsies I am seeing the issue with the tags.

**Comment by tdphillips** [comment]
Pushed a fix for tag styling.

**Pull request merged**
