### PR TITLE
[PD-1090] Removed unused import.

### PR DESCRIPTION
**Pull request by aspidites**
Turns out I had already done most of this already. The only real thing that remains would be to pass the path and data into the constructor, but the tests are running, so I'm not inclined to change them.

### CODE REVIEW

**Comment by tdphillips** [comment]
The tests are no longer running. Are you planning on changing something or would that come later?

**Comment by aspidites** [comment]
@tdphillips I don't have any other changes going on top of this. I basically audited all test files and found this PEP8 change.

**Comment by tdphillips** [comment]
Was unsure if "the only real thing that remains" meant you were going to do that or not.

**Comment by aspidites** [comment]
Oh sorry. That was meant more as "It's not worth doing as part of this
ticket.". Should have been clearer.

**Pull request merged**
