### PR TITLE
Reporting CSV

### PR DESCRIPTION
**Pull request by aspidites**
Can be merged after my other stuff I suppose. CSV export works and is ridiculously fast.

### CODE REVIEW

**Comment by JLMcLaugh** [comment]
Merge conflicts

**Comment by JLMcLaugh** [comment]
Is this failing from a dependency or something else?

**Comment by aspidites** [comment]
@JLMcLaugh I'm assuming it was something that got changed in another branch. I've pulled recently and tests seem to be passing now.

**Comment by almathew** [comment]
Jenkins had a rough weekend.

**Pull request merged**
