### PR TITLE
Pd 3537 assessment create custom filter components

### PR DESCRIPTION
**Pull request by iartemiev**
## What's this PR do?
* custom FilterComponents (with optional multi-select functionality)
* FilterBar - which displays all selected filters and allows for removal of either individual or all selected filters.
* GET contacts from API

## Screenshots (if appropriate)
screen shot 2017-08-01 at 4 59 05 pm

## How should this be manually tested?
1. Go to partner assessment
2. Try selecting various combinations of filters.
3. Note that the star filter is single-select
4. Try clearing filters individually, as well as by using the 'clear all' button

## Any background context you want to provide?
The styling is still preliminary and will require some polish...

### CODE REVIEW

**Comment by aljordan82** [comment]
It seems that using the keyboard arrow keys to navigate the dropdown is skipping some menu items

**Comment by iartemiev** [comment]
Good call, I'd forgotten about that. I'll fix it shortly

**Comment by aljordan82** [comment]
Could it be that there are multiple listeners for dropdown menu keydown event?

**Comment by iartemiev** [comment]
I have not bound anything to `keyDown` myself... 
The only dropdown event I'm binding to is `onSelect`

**Pull request merged**
