### PR TITLE
Fixed time format.

### PR DESCRIPTION
**Pull request by aspidites**
Without this, all PR branches will fail.

### CODE REVIEW

**Comment by almathew** [comment]
Not sure - won't this cause things to fail if the date is a two digit number?

**Comment by aspidites** [comment]
What did you do differently, @almathew , since you fixed this in your branch?

**Comment by almathew** [comment]
Probably not the best way to fix it, but:
https://github.com/DirectEmployers/MyJobs/pull/1127/files#diff-e337d3bf994a8853913c57a312419debR314

**Comment by aspidites** [comment]
@almathew  and you're right. No go with 2 digits days.

**Comment by aspidites** [comment]
Ah, I see what you did. Hmm.. that would work. Feels redundant. I'll use it for now though.

**Comment by aspidites** [comment]
Investigated further, and unless we start using padded integers, manually constructing the date string as you did is the proper solution.

**Comment by aspidites** [comment]
@almathew I prefer the format variety, but copied yours verbatim as not to introduce merge conflicts with your branch.

**Pull request merged**
