### PR TITLE
[PD-2295] Locations and Comm Rec Types

### PR DESCRIPTION
**Pull request by aspidites**
This is just #2233 pointing to QC instead of @darrint's branch, which was already merged.

### CODE REVIEW

**Comment by aspidites** [comment]
I think we confirmed in the last ticket that this was ready to go, with the caveat that some concerns are overlapping. Decoupling that functionality will be handled in a different ticket that @JLMcLaugh made, which is assigned to @darrint .

**Comment by koonsies** [comment]
When I merge quality control into this branch and run the code, I'm getting an error from the api/help call, as well as when I try to run the report.

`TypeError: __init__() got an unexpected keyword argument '' `

The report appears in the list after I refresh the page, but it is always empty. Is this happening to anyone else?

**Comment by aspidites** [comment]
Runs fine for me. Did you rerun gulp build?

**Comment by aspidites** [comment]
I will say I was getting that error a few commits back, so you may be running a stale branch.

**Comment by koonsies** [comment]
Ah, that did the trick. I thought I had done that already.. It seems I was wrong.

**Pull request merged**
