### PR TITLE
Impersonate Onto Staging

### PR DESCRIPTION
**Pull request by koonsies**
## What's this PR do?
This PR adds a ajax-select control to the analytics platform to allow a user with the "impersonate analytics" activity to impersonate another company and view their analytics.

## Where should the reviewer start?
Any analytics view.
https://secure.my.jobs/analytics/view/main/

## How should this be manually tested?
Using shell or the django admin, add the app access of "Impersonation" to a company that you are admin to.

After that, select that company in the topbar and head to Analytics.

There should be a dropdown in the upper left corner. Enter the name of a company that has analytics data (or one that doesn't).

Notice how the data displayed changes based on what company is selected.

## Any background context you want to provide?

I dunno. It's 4:43. Maybe I'll add more to this later.

### CODE REVIEW

**Comment by almathew** [comment]
I've just shared an error I'm getting with @koonsies 

```[26/Jun/2017 10:54:37] ERROR [django.request:284] Internal Server Error: /analytics/api/dynamic
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/MyJobs/myjobs/decorators.py", line 253, in wrap
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/MyJobs/analytics/api.py", line 207, in dynamic_chart
    report, group_by, remaining_dimensions = report_for_request(request)
  File "/MyJobs/analytics/utils.py", line 127, in report_for_request
    print 'impersonation: %s ' % impersonated_company.name
AttributeError: 'NoneType' object has no attribute 'name'````

**Comment by tdphillips** [comment]
You can impersonate companies that don't have the appropriate app-level access. Is that okay?

**Comment by almathew** [comment]
Nevermind. @koonsies helped me fix it. It's just me.

**Comment by almathew** [comment]
Works for me testing locally. Biggest concern is how messed up the QC version of this branch is.
👍

**Pull request merged**
