### PR TITLE
[PD-909] Hide no sitepackage errors

### PR DESCRIPTION
**Pull request by aspidites**
The backend stuff exists still, but is no longer displayed in the front end.

### CODE REVIEW

**Comment by aspidites** [comment]
Reverts my changes to page view permissions. We're supposed to be talking about it Monday to get a better idea of what should and shouldn't be viewable.

**Comment by almathew** [comment]
You changed `static/postajob.159-15.js → static/postajob.160-2.js`. Did you ever update the templates to reflect that?

**Comment by almathew** [comment]
Nevermind. I see it in the other pull request.

**Comment by almathew** [comment]
Now has merge conflicts.

**Comment by aspidites** [comment]
Yeah, sorry about that. I guess I made these chances on the other PR's branch instead of master?

**Pull request merged**
