### PR TITLE
Mx record checks

### PR DESCRIPTION
**Pull request by almathew**
Just up for review. Don't merge until we can confirm `make_mx_record()` is working

### CODE REVIEW

**Comment by aspidites** [comment]
> Don't merge until we can confirm make_mx_record() is working
And how do we do that?

**Comment by almathew** [comment]
I should be testing it tomorrowish.

**Comment by tdphillips** [comment]
I ran make_mx_record for indianapolis.jobs. `dig indianapolis.jobs MX` returns nothing (and probably won't for 24-48 hours) but specifying your name server makes the record show up (`dig @ns.1454.awsdns-53.org indianapolis.jobs MX`).

`dig @ns-1454.awsdns-53.org indianapolis.jobs MX`

**Comment by tdphillips** [comment]
What do you know, it was more like ten minutes than 24 hours.

**Comment by almathew** [comment]
Does it point to sendgrid correctly?

**Comment by tdphillips** [comment]
Looks like it. It's the same as the record for my.jobs.

**Comment by tdphillips** [comment]
Removed the DO NOT MERGE label but I would like #1605 to be looked at first.

**Pull request merged**
