### PR TITLE
Pd 1504

### PR DESCRIPTION
**Pull request by mklauber**

### CODE REVIEW

**Comment by tdphillips** [comment]
Conflicts.

**Comment by mklauber** [comment]
I'm aware.  I'm just trying to figure out why, because there aren't any when I pull the branches locally.

**Comment by aspidites** [comment]
I don't think this is right. It has all my log in renaming stuff in it.

**Comment by aspidites** [comment]
@mklauber  it should look like [this](https://github.com/DirectEmployers/MyJobs/compare/master...pd-1504-master?expand=1)

**Pull request closed without merging**
