### PR TITLE
[PD-1554] New Reporting Models

### PR DESCRIPTION
**Pull request by aspidites**
Updates to ERD from @haliscooper's updated ERD (see epic)

# Models
models

# ERD
erd5

# Changes
- `column` is now nullable on `ConfigurationColumn`
- added `default_value` and `filter_only` to `ConfigurationColumn`

@haliscooper, does the new ERD look correct? I'll leave it to the rest of the team to validate the models are correct.

### CODE REVIEW

**Comment by aspidites** [comment]
For the confused, @tdphillips's comment is a carry-over from the other branch and has been addressed already. Not sure why it's showing up here.

**Comment by haliscooper** [comment]
Looks goiod

**Comment by aspidites** [comment]
Talking with @haliscooper  and @fezick , may need to change some things.

**Comment by aspidites** [comment]
Models are changing.

**Comment by aspidites** [comment]
Ugh, that DO NOT MERGE should have been removed early last Friday

**Pull request merged**
