### PR TITLE
PD-3869 valid ssl cert

### PR DESCRIPTION
**Pull request by iartemiev**
## What's this PR do?
Creates valid self-signed SSL certs (as per Chrome 61+) for use with our devServer

## Screenshots (if appropriate)
image

## Instructions:
• run `dk initrevproxycerts`

## macOS:
• open `dk2/revproxy/certs/secure.rootCA.pem` in Keychain Access
• Double-click on the newly imported cert within Keychain Access
• Select **Always Trust** When using this certificate. See screenshot:

image

• Close the window. It will ask you for your password - enter it. 
• Close Keychain Access

## Linux:
• `sudo apt-get install libnss3-tools`
• From the root of the project run: 
`certutil -d sql:$HOME/.pki/nssdb -A -t "TC,C,T" -n secure.rootCA -i dk2/revproxy/certs/secure.rootCA.pem`
• Confirm that the new cert shows up with: `certutil -d sql:$HOME/.pki/nssdb -L`

• Firefox > Preferences > Privacy & Security > Security > View Certificates > Authorities
• Import... select `MyJobs/dk2/revproxy/certs/secure.rootCA.pem`
• Check "This certificate can identify websites." and click **Ok**
• Restart Chromium and/or Chrome

## Windows:
`certutil –addstore -enterprise –f "Root" <path\to\certificatefile>`

## After Importing the cert:

• Stop your local web server and the dev server
• Run `dk backgroundstop && dk background`
• Restart the web and dev servers
• Navigate to `secure.my.jobs` and you should see a green **Secure** label next to the URL

If it didn't work, try restarting your computer. Sometimes the certs get cached by the browser.

This solution works in Chrome and Safari. 

In Firefox, you will still need to add exceptions for these certs by navigating to `secure.my.jobs` and `secure.my.jobs:8080`.

### CODE REVIEW

**Comment by aljordan82** [comment]
This is awesome, it works!

**Comment by iartemiev** [comment]
@aljordan82 Awesome! Now I just want to make sure that it works for the Linux folks (:

**Comment by iartemiev** [comment]
@tdphillips, @koonsies could either of you try this, please?

**Comment by tdphillips** [comment]
My system doesn't like any of the generated keys. I'm on 61.0.numbers.
2017-10-06-143735_532x209_scrot

**Comment by iartemiev** [comment]
@tdphillips I might need to convert the .pem to something else. Which flavor of Linux are you running?

**Comment by iartemiev** [comment]
Linux users: please see updated instructions. I was able to get it working using that method on Ubuntu:16.04

**Comment by iartemiev** [comment]
**On macOS if you install the new root cert and then revert back to the old (non-SHA1, unsigned certs), Chrome will think that you're being MITM'd and might not let you navigate to secure. 
To mitigate this go to Settings > Advanced > Reset and Reset Chrome**

**Comment by tdphillips** [comment]
I wonder if not using Chromium is my problem. Following the instructions, I get a green lock in Firefox. I install Chrome directly from Google, however, and am still getting a privacy error prompt.

**Comment by iartemiev** [comment]
@tdphillips I had unintentionally left out some instructions. Please see the updated steps. 
I've verified that it works in both Chromium and Chrome!

**Pull request merged**
