### PR TITLE
Pd 3614 nuo sub navigation

### PR DESCRIPTION
**Pull request by strempe**
## What's this PR do?
- (Desktop View) Moves navigation for DE 'Non-User Outreach' application into a top sub navigation.
- (Mobile View) Moves navigation into a dropdown sub navigation.
screen shot 2017-08-25 at 10 58 28 am

## Screenshots (if appropriate)
screen shot 2017-08-25 at 10 55 42 am

## Where should the reviewer start?
- My Apps > PRM > Non-User Outreach

## How should this be manually tested?
- When selecting 'Outreach Records', display should show the record list 
- When selecting 'Inbox Management', display should show Outreach Inboxes 

## Any background context you want to provide?
- Mobile View: We will eventually be moving filters to the top of the screen, in a dropdown.

### CODE REVIEW

**Comment by koonsies** [comment]
Was Aladeen going to create a feature branch for the navigation moves? That would probably be better than aiming this at quality-control, in case something happens and we cannot refactor all navigation before the end of the sprint.

**Comment by koonsies** [comment]
Do we want to add a "active navigation" entry into the Navigation menu? So we can highlight the navigation/page they are currently on.

**Comment by koonsies** [comment]
I'm having some dialogue box issues on NUO. Not sure if it was introduced by this PR. When you click "Review" on one of the records, you get a "Are you sure you want to navigate.." dialogue. IIRC, we removed this dialogue completely when we implemented history on NUO, so I'm not sure why it's popping up.

Beyond that, history seems to be messed up on this branch. I'm gonna verify these issues don't exist in QC.

**Comment by koonsies** [comment]
I am a bit puzzled, but the history handling I believe I had added to NUO -> Process Record is now missing. That said, at the very least the modal needs to be fixed.

**Comment by aljordan82** [comment]
Looks good!

**Comment by aljordan82** [comment]
@koonsies We are pushing this to a feature branch.
We fixed the dialog issues and missing routes.
The PR should be good now.

**Pull request merged**
