### PR TITLE
added permissions on dseo topbar [PD-901]

### PR DESCRIPTION
**Pull request by galitskyd**
Posting Access and Product Access
screen shot 2015-01-02 at 8 24 08 am

Posting Access False
screen shot 2015-01-02 at 8 23 00 am

Posting Access and Product Access False
screen shot 2015-01-02 at 8 23 25 am

### CODE REVIEW

**Comment by almathew** [comment]
How does this look with less permissions? Does the topbar resize well?

**Comment by aspidites** [comment]
@galitskyd screenies?

**Comment by almathew** [comment]
@fezick do you approve of screenshots?

**Comment by aspidites** [comment]
What about just product_access false?

**Comment by galitskyd** [comment]
product_access false 
screen shot 2015-01-02 at 11 39 51 am

**Comment by aspidites** [comment]
I can't test this further since /posting/admin throws 404 (staging data) and /posting/list only shows Product Listing.

Screenshots look correct though.

**Pull request merged**
