### PR TITLE
Fix utils

### PR DESCRIPTION
**Pull request by aspidites**
Some linting and declaring functions outside of the original object creation. Only errors  are because i'm using var instead of let or const, which I am doing because this file isn't being handled by gulp.

### CODE REVIEW

**Comment by koonsies** [comment]
:+1: Tested and still works as expected

**Comment by aspidites** [comment]
Bleh. Need to do more thorough testing. I'm sure this works in the perfect use case, but something about what I'm doing is causing me problems locally.

**Comment by aspidites** [comment]
Nvm. It's just on one of my branches, which means I need to fix the branch.

**Comment by aspidites** [comment]
OK. located the issues I was having locally. Definitely not due to this pr.

**Pull request closed without merging**
