### PR TITLE
Django says this is missing

### PR DESCRIPTION
**Pull request by tdphillips**
## What's this PR do?
Adds a migration that Django complains about
## Any background context you want to provide?
While ensuring my database was up to date, Django helpfully informed me that there are model changes that are not yet reflected in a migration. I didn't want this change to get caught up in an unrelated migration so here we are.

### CODE REVIEW

**Comment by tdphillips** [comment]
@almathew, any problem with this? The original change is yours, I believe, and I wanted to make sure we don't expect this to cause any issues.

**Comment by almathew** [comment]
No I'm fine with the change. I'm mostly just confused on how this only just got picked up now.

**Comment by tdphillips** [comment]
Jenkins doesn't like this migration. I'll play with it a bit and see what happens.

**Comment by tdphillips** [comment]
Tried to execute this migration myself. Was notified that there were more model changes that didn't have a migration. Generating them resulted in a duplicate analytics migration.

¯\\\_(ツ)\_/¯

**Pull request closed without merging**
