### PR TITLE
PD-2004 cleaned layout of User and Role edit views

### PR DESCRIPTION
**Pull request by misterjonscott**
## Overview

Minor tweaks to layout and styling, per ticket PD-2004.

## Testing

The visual changes should be different than the attached, noted, version, and changes should be noted in both Users-> Edit, as well as Roles -> Edit.

### CODE REVIEW

**Comment by lemniscate613** [comment]
Something to keep in mind:


screen shot 2016-01-05 at 3 34 30 pm

**Comment by misterjonscott** [comment]
I'm updating per Daniel's observation.

**Comment by aspidites** [comment]
is this still WIP?

**Comment by aspidites** [comment]
Warnings:

```
(myjobs)gulp ➤ gulp                                                                                                                                              git:PD-2004
[08:43:44] Using gulpfile ~/projects/myjobs/gulp/gulpfile.js
[08:43:44] Starting 'bundle'...
[08:43:44] Starting 'lint'...
[08:43:44] Starting 'test'...
.............................

29 specs, 0 failures
Finished in 0.1 seconds
[08:43:46] Finished 'test' after 2.29 s
[08:43:55] chunk    {0} vendor.js (vendor) 775 kB [rendered]
chunk    {1} reporting.js (reporting) 286 kB {0} [rendered]
chunk    {2} nonuseroutreach.js (nonuseroutreach) 192 kB {0} [rendered]
chunk    {3} manageusers.js (manageusers) 254 kB {0} [rendered]
[08:43:55] Finished 'bundle' after 11 s
[08:43:57] 
src/manageusers/Role.jsx
  265:9  warning  Unexpected confirm  no-alert

src/manageusers/User.jsx
  197:9  warning  Unexpected confirm  no-alert

✖ 2 problems (0 errors, 2 warnings)

[08:43:57] Finished 'lint' after 13 s
[08:43:57] Starting 'build'...
[08:43:57] Finished 'build' after 7.09 μs
[08:43:57] Starting 'default'...
[08:43:57] Finished 'default' after 4.62 μs
(myjobs)gulp ➤                                                       
```

**Comment by tdphillips** [comment]
Those have been there for a while now.

**Comment by aspidites** [comment]
Yeah, but I'd like to stop being the case.

**Comment by aspidites** [comment]
Really, I'd prefer a -Wall option, but maybe that's just me.

**Comment by lemniscate613** [comment]
FYI, these "no-alert" warnings are a configurable option in JSLint. Our config prefers we don't use `confirm()` at all (e.g. we're using them to confirm that the user wishes to delete another user). I implemented `confirm()` temporarily until we get modals figured out in Bootstrap 3 in IE8 (there was an issue with these the last time I investigated). @darrint is looking into it now.

**Comment by aspidites** [comment]
Ah. I'm fine with this as long as something somewhere is tracking that we either need to a) disregard this warning in our config or b) come up with a cross-browser solution.

**Comment by tdphillips** [comment]
Merging this as it appears that confirm is a separate issue. I'd like to see a ticket for that, however.

**Pull request merged**
