### PR TITLE
Comparing custom.scss to custom.css

### PR DESCRIPTION
**Pull request by JLMcLaugh**
This is for comparing the new custom.scss file to the old custom.css. Make sure you're adding the w=1 parameter to ignore leading whitespace.

### CODE REVIEW

**Comment by JLMcLaugh** [comment]
This should go without saying, but don't merge this.

**Comment by JLMcLaugh** [comment]
https://github.com/DirectEmployers/MyJobs/pull/2512/files/?w=1

**Comment by huy-nguyen-colorado** [comment]
This custom.css file looks different than the compiled custom.css on my machine.

**Comment by JLMcLaugh** [comment]
I probably didn't explain this well. I just overwrote static/custom.css with the new src/sass/custom.scss file from @huy-nguyen-colorado's PR here: https://github.com/DirectEmployers/MyJobs/pull/2510/files

It's not perfect, but it's easier to compare what's changed than looking at the 5000+ line files.

**Pull request closed without merging**
