### PR TITLE
Fix a bug, city field not refreshing

### PR DESCRIPTION
**Pull request by aljordan82**
## What's this PR do?
Fix bug in SearchInput.jsx
The bug happens because the SearchInput constructor I called only once
any subsequent updates to the SearchInput “value” prop were ignored.

### Front-End

- [ ] Works on IE 11 and Edge
- [ ] Works on Mobile
- [ ] Unit tests added or ticket exists to add tests

### CODE REVIEW

**Comment by aljordan82** [comment]
@koonsies last attempt to fix this caused a regression and it needed a hotfix.

**Comment by koonsies** [comment]
Code looks sound. I'll review this after I finish the common-action PR

**Comment by tejaswinigutti31** [comment]
The fix actually make the clone that was broken work properly for city field

**Comment by koonsies** [comment]
I don't remember the regression you mentioned. However, this seems to work fine.

**Pull request merged**
