### PR TITLE
[PD-2010, PD-2011, PD-2012] Fix topbar-new mobile issues, which uses Bootstrap3

### PR DESCRIPTION
**Pull request by lemniscate613**
Overview
=========

New projects (like Manage Users) use Bootstrap 3, but this broke the toolbar on mobile.

This PR fixes the "[hamburger](https://en.wikipedia.org/wiki/Hamburger_button)" button:

screen shot 2015-12-23 at 11 23 32 am

And the expanded view:

screen shot 2015-12-23 at 11 23 53 am

Review
=========

* Run `gulp build`
* Visit https://local/manage-users
* Make browser smaller

Home
=========

It's tiny.

home

### CODE REVIEW

**Comment by koonsies** [comment]
screen shot 2015-12-28 at 8 36 18 am

This may be out of scope for this PR, but it's worth noting that word wrap doesn't work correctly in the menu.

**Comment by tdphillips** [comment]
In a PR for fixing issues with the topbar, I don't think that's out of scope.

**Comment by misterjonscott** [comment]
The overflow problem can be solved with by adding:
```
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
```
to the (.topbar #nav ul#pop-menu li a) style set.

**Comment by misterjonscott** [comment]
screen shot 2015-12-29 at 2 53 26 pm
The submenu icons could use some padding, from their titles.  Consider adding:
```
margin-left: 10px; 
```
to (#employer-tools:after, #settings-link:after, #mobile-company-select > a:after), or whatever spacing is brand compliant.

**Comment by lemniscate613** [comment]
Good point @koonsies. That was a pre-existing issue site-wide. I fixed it though (thanks for teaching me about `text-overflow: ellipsis;` @misterjonscott).

It works on 1st level:

screen shot 2015-12-30 at 9 40 52 am

And 2nd:



screen shot 2015-12-30 at 9 40 56 am

As for @misterjonscott's second point, I couldn't replicate the issue:

screen shot 2015-12-30 at 9 47 35 am

It should be good to go now.

**Comment by misterjonscott** [comment]
Look great.  Merging.

**Pull request merged**
