### PR TITLE
Added is_site_family boolean to site tags to allow for site families [PD-1155]

### PR DESCRIPTION
**Pull request by almathew**
Migration 0014 was a little messed up, so I had to fix that as well.

### CODE REVIEW

**Comment by aspidites** [comment]
Looks good other than that pesky duplicate transaction thing. I had to do the same in my other branch.

**Comment by aspidites** [comment]
Seems fine. Are we concerned about the implications of making a site tag a site family, tagging sites as such, then making that tag a regular one again? That is, what does it mean operationally to convert a site tag to a site family and back again? Anything? Nothing?

**Comment by almathew** [comment]
Demoting via checkbox is fine. It will be the fastest way to handle the people who don't renew and then renew three weeks later.

**Comment by tdphillips** [comment]
This doesn't differentiate which site is the parent, does it?

**Comment by almathew** [comment]
"Groups" were never going to be a good way to do that. @JLMcLaugh and I were discussing namespacing which would be the best way to denote the parent. Unfortunately this is something that I can explain what my intentions were but until it has an actual use case it will be a complete guess as to whether or not it works.

I'm open to other suggestions for how to do this, but the only other alternative I see is adding another model/admin, which was something that we were trying to avoid.

**Comment by almathew** [comment]
Alternatively, I can add a relationship with SeoSite that will allow you to explicitly denote parent without any fancy namespacing. Because everything needs a relationship with SeoSite.

**Comment by aspidites** [comment]
Or you could do something horrible and add yet another field to this model "is_parent".

**Comment by almathew** [comment]
Now with more foreign key.

**Pull request merged**
