### PR TITLE
[PD-2496] Multiselect -> Tag Select

### PR DESCRIPTION
**Pull request by aspidites**
This does a few things:

- replaced RolesMultiselect with TagSelect
- replaced lodash-compat with lodash and bumped version[1]
- deleted TagSelectController
- minor formatting to clean up some longer lines
- stopped reaching into a child component for state values
- stopped specifying state that didn't change, as setState does a shallow copy[2]

[1] I spoke with @JLMcLaugh about this with respect to IE 8 compatibility. I ran through the apps and did a few random things to make sure they still worked. Let me know if this breaks IE 8 in any obvious ways.
[2] The next PR I work on will start using redux to manage state in the users portion of the app

### CODE REVIEW

**Comment by darrint** [comment]
Message:
        Cannot find module 'common/email-validators'
    Details:
        code: MODULE_NOT_FOUND
    Stack:
    Error: Cannot find module 'common/email-validators'
        at Function.Module._resolveFilename (module.js:339:15)
        at Function.Module._load (module.js:290:25)
        at Module.require (module.js:367:17)
        at require (internal/module.js:16:19)
        at Object.<anonymous> (/opt/jenkins/workspace/Fixing-PRs/MyJobs/gulp/src/nonuseroutreach/reducers/inbox-management-reducer.js:2:44)

**Comment by darrint** [comment]
Reporting fails on Chrome with this:

    Uncaught TypeError: (0 , _lodash.sortByAll) is not a function

https://github.com/lodash/lodash/wiki/Changelog#v400 ... grep for `sortByAll`

Also, the module loading problem is reproduced by running the unit tests, `gulp watch-tasks watch`

**Comment by aspidites** [comment]
Bleh, I'm getting stuff locally as well.

**Comment by aspidites** [comment]
Went a different route. Should be a bit safer, IE8 wise.

**Pull request merged**
