### PR TITLE
PD-3460 analytics duplicate xhr requests on load

### PR DESCRIPTION
**Pull request by iartemiev**
## What's this PR do?
Removes the redundant API calls on initial load of Analytics

## Where should the reviewer start?
1. `api.js`
2. `page-loading-actions.js`

## How should this be manually tested?
1. Open Dev Tools -> Network
2. Navigate to Analytics
3. There should only be 1 call to the `/available-reports` endpoint (formerly there were 3).

### CODE REVIEW

**Comment by koonsies** [comment]
Merge conflicts

**Comment by iartemiev** [comment]
Merge conflicts resolved

**Comment by koonsies** [comment]
It looks like this PR is based off of https://github.com/DirectEmployers/MyJobs/pull/3221

Adding the DNM label here until that PR is resolved.

**Comment by aljordan82** [comment]
I can't get the  Timeline chart to open.

**Pull request merged**
