### PR TITLE
[PD-874] Copied another change from myjobs template to dseo template."

### PR DESCRIPTION
**Pull request by aspidites**
Bug fix that got missed when templates diverged for postajob.

### CODE REVIEW

**Comment by fezick** [comment]
tests failed

**Comment by aspidites** [comment]
@fezick sure it's unrelated. Ashley said there's some time related test thats going to cause all tests to fail.

**Comment by aspidites** [comment]
@fezick  I'll push again when #1129 or #1127 gets merged. The former fixes the failing test explicitly (a separate PR as it affects everyone), while the latter also introduces some block-related stuff. 

@almathew @galitskyd @tdphillips @fezick @mklauber @JLMcLaugh : If #1127 does get merged first, #1129 can safely be closed.

**Comment by aspidites** [comment]
Waiting on #1129 or #1127 to fix tests, then updating this.

**Pull request merged**
