### PR TITLE
PD-3670 - UX - remove Gulp

### PR DESCRIPTION
**Pull request by iartemiev**
## What's this PR do?
Step 2 of https://github.com/DirectEmployers/MyJobs/pull/3461

I renamed the **gulp** dir to **secure**. Just the first thing that came to my mind. I'm open to suggestions though

### CODE REVIEW

**Comment by iartemiev** [comment]
Seems that only some python tests are failing

**Comment by darrint** [comment]
Any reason not to just move everything to the root? I don't think the secure name is going to hold up. I may have missed some discussion though.

**Comment by iartemiev** [comment]
@darrint The only issue I see with that is that there are already a few dozen (mostly python) files in the root, so things like our `package.json`, `webpack.config`, `.babelrc`, etc. might become a bit more difficult to find. I personally like having the front end in a separate dir from an organizational perspective... I could likely be swayed though (:

@aljordan82, @mwarnsleyDE - what do you guys think?

**Comment by darrint** [comment]
Back in the day I got a few complaints because of the fact that it was in a subdir.

**Comment by mwarnsleyDE** [comment]
@iartemiev and @darrint I'm not too familiar with how the secure or other domains relate to the folder structure but I can say I'm all for having the front end in a different directory compared to the backend. I do think it's easier to find and honestly for me I think finding some of the front end stuff even in django right now hard to find because of how many files we currently have. Right now I think it's easier to find all of the react projects because we know it's the only thing that goes into the gulp folder and nothing else so I think that structure makes it easier to navigate the code base. I don't know how that relates to anything else as far as domains or anything like that but if we could I think it would be easier keeping them separated.

**Pull request merged**
