### PR TITLE
Pd 3276 adding first viewed on primary dimension

### PR DESCRIPTION
**Pull request by tejaswinigutti31**
## What's this PR do?
Adding first viewed on as a primary dimension to Site Owner and Job Owner Syndication.
## Screenshots (if appropriate)
screen shot 2017-06-08 at 4 23 38 pm

## Any background context you want to provide?

- [x] Data migration for existing dynamic reports.
- [ ] ~~Remove old tables.~~ Don't do this.
- [ ] Find and fix more regressions.
- [x] Rearrange the fields originally requested in the PR.
- [ ] `split(..., 3)` should have been `split(..., 2)`
- [ ] Fix JS unit tests.

### CODE REVIEW

**Comment by tejaswinigutti31** [comment]
This one is based on PD-3340-adding-reqid-reporttype.

**Comment by tejaswinigutti31** [comment]
PD-3287 changing user-agent to browser - added as part of this PR

**Comment by tejaswinigutti31** [comment]
I have fixed js Unittests and split(..., 2)

**Comment by koonsies** [comment]
This PR introduced a lot of old (invalid) code from reporting back into QC. It will need to be reverted and properly merged with the react-router changes in order to function.

**Pull request merged**
