### PR TITLE
Task timeouts

### PR DESCRIPTION
**Pull request by mklauber**

### CODE REVIEW

**Comment by mklauber** [comment]
Can one of the admins verify this patch?

**Comment by mklauber** [comment]
Can one of the admins verify this patch?

**Comment by mklauber** [comment]
test please

**Comment by tdphillips** [comment]
test please

**Comment by tdphillips** [comment]
test please

**Comment by mklauber** [comment]
test this please

**Comment by aspidites** [comment]
If I understand this correctly, we version bump celery in order to get `soft_time_limit`, which IIRC is meant to address the random hangs we've been getting since moving to solr cloud?

Code changes themselves look fine, just trying to remember the motivation since I don't see a tagged jira ticket.

Also, rather than the PEP8 changes, wouldn't the single test command ( @tdphillips, I'd love a reminder of the syntax) be more useful here?

**Comment by tdphillips** [comment]
I don't know if single test works anymore. In any case, using it doesn't update the status on GitHub.

**Pull request merged**
