### PR TITLE
[PD-3470] fix reporting export - criteria sheet

### PR DESCRIPTION
**Pull request by vigowei**
## What's this PR do?
convert raw data from request to human readable format in the criteria sheet.

## Screenshots (if appropriate)
before:
image

after:
image

## Where should the reviewer start?
`myreports/views.py` Line#750

## How should this be manually tested?
Go to PRM or TJD, pull any reports with different criteria and download the excel, check all criteria are represented correctly.

## Any background context you want to provide?
Added adorned filters as an additional argument to 2 functions, to help us translate some fields.
refactored the xlsx writer a bit.

### CODE REVIEW

**Comment by darrint** [comment]
Just ran a report on partners with two tags and got this in the criteria sheet:


tags | [[{'hexColor': u'808A9A', 'display': u'Disability', 'value': u'Disability'}, {'hexColor': u'5EB94E', 'display': u'Veteran', 'value': u'Veteran'}]]
-- | --

**Comment by vigowei** [comment]
closing while fixing bugs reported

**Comment by tejaswinigutti31** [comment]
The criteria sheet has been fixed to display appropriate format. The above scenario does work and is displayed as below:
image

**Comment by darrint** [comment]
Looks good now. Waiting for tests.

**Pull request merged**
