### PR TITLE
[PD 3562] form validation location rule

### PR DESCRIPTION
**Pull request by mwarnsleyDE**
## What's this PR do?
PR fixes the space issue in the regex for validating a rule location

## Screenshots (if appropriate)
N/A

## Where should the reviewer start?
Start inside of the TJD application in a custom CBO

## How should this be manually tested?
Pull down the repository. Go into manage contacts from TJD application. Add a Rule of location and type New York, NY. Before it would throw an error for the space in between New York but now it will save

## Any background context you want to provide?
https://directemployersfoundation.atlassian.net/browse/PD-3562

### CODE REVIEW

**Comment by mwarnsleyDE** [comment]
@aljordan82 I'm not 100% sure on the requirements to be honest. I don't know if Jason Sole ever actually had any or not to be honest.

**Comment by mwarnsleyDE** [comment]
@aljordan82 that should fix it

**Comment by aljordan82** [comment]
@mwarnsleyDE Do we need to account for 3 words cities? such as"North Little Rock, AR"?

**Comment by aljordan82** [comment]
@mwarnsleyDE I think this will do `/^[a-z]+([ ]{1}[a-z]+)*, [a-z]{2}$/i`

**Comment by mwarnsleyDE** [comment]
@aljordan82  updated

**Pull request merged**
