### PR TITLE
[PD-2581] - sass-demo

### PR DESCRIPTION
**Pull request by huy-nguyen-colorado**
The purpose of this PR is to demonstrate and lay the foundation for the usage of sass (css preprocessor) in our project. 

Within the: gulp > src  directory, I created a directory call "sass", this is where our .scss files will live (in reality, it can live anywhere, I picked this location for convenience).  In the sass directory, I created a file called "custom.scss" which is the sass version of the pre-existing "custom.css" file that lives in the static directory. I also created a "_media_queries.scss" file and a "_variables.scss" file in the sass folder to demonstrate sass's ability to use variables, mixin functions, and imports.

In the package.json file's "dependencies" section, I added the "node-sass" module to allow NPM to compile sass to css, and the "onchange" module to allow NPM to watch and execute scripts if the  sass files changes.

In the "scripts" section of the package.json file, I added the following scripts: "compile-sass" to compile .scss files in the sass directory and put the compiled .css file in the static directory (only because this is where custom.css lives, again, this is a demo PR targeting the custom.css file), "compile-minify-sass" to compile and minify css (will be deprecated once we have a webpack task for this), and "watch-sass" to watch compile sass during development, just a convenience feature.  To run these scripts, cd to the "gulp" directory, npm install the new modules, and run the respective scripts.  

Going forward, we can leverage sass for much more, but the most important thing is to prevent CSS bugs.

### CODE REVIEW

**Comment by tdphillips** [comment]
Was it intentional to check in the compiled file?

**Comment by huy-nguyen-colorado** [comment]
Yes, because at this point in time, we do not have a mechanism by which to compile the sass on the build server via webpack yet, therefore the developer is still responsible for checking in the compile css file.

**Comment by huy-nguyen-colorado** [comment]
Furthermore, had I or another developer not check in the compiled css file, then the other developers that will have run the "compile-sass" or "compile-minify-sass" NPM script to compile and send the custom.css file to the proper location.

**Comment by huy-nguyen-colorado** [comment]
I've removed the onchange NPM module and I've removed the sass-watch NPM script which depended on the onchange module.

**Comment by mklauber** [comment]
:+1:

**Comment by tdphillips** [comment]
Shrinkwrap needs updating.

**Pull request merged**
