### PR TITLE
Pd 3565 sub navigation feature branch

### PR DESCRIPTION
**Pull request by aljordan82**
## What's this PR do?
Reworked the Navigation in most sites.
## How should this be manually tested?
Test all pages in all apps in multiple screen sizes.

### CODE REVIEW

**Comment by koonsies** [comment]
Conflicts

**Comment by koonsies** [comment]
typo
button formatting lost
nuo add record button lost styling
mobile formatting problems comm rec review
not obious how to get to contacts
prm main page gap

**Comment by koonsies** [comment]
Beyond the above notes, I also saw some other issues.

1) I can't confirm this, as I can only use the emulator, but the drop down menu links for the react apps don't work in the Chrome mobile emulator.

2) When the window is shrunk to a small size, but not in emulator mode, the drop down menu links for navigation (in react) don't close after making a selection

3) On Manage Users, anything you do redirects to Overview.. If you click "Edit" on a role, then "Cancel", you head to Overview. Same with Save, Delete, etc.

**Comment by koonsies** [comment]
I'm still reviewing, but that is what I have so far.

**Comment by aljordan82** [comment]
@koonsies fix User Managment and styles issues.
I am not sure how can I verify the mobile dropdown/React, but I don't see why it wont work.

**Comment by aljordan82** [comment]
@koonsies I can't reproduce point 2. (Menu no closing in react/ not emulator)

**Comment by koonsies** [comment]
Alright, that's fine. Let's just be sure to test it via a mobile device after QC deploy.

**Comment by aljordan82** [comment]
@koonsies @tdphillips 
There is one remaining issue in Edit Tag Page, there is tertiary nav in it. I don't know how to git rid of it. Also the "Tag Management" needs to be set as Active.
screen shot 2017-09-15 at 3 53 28 pm

**Comment by tdphillips** [comment]
Fixed some tag management issues.

**Pull request merged**
