### PR TITLE
[PD-916] Removed code that was generating invalid html

### PR DESCRIPTION
**Pull request by aspidites**
Bad HTML is bad.

### CODE REVIEW

**Comment by galitskyd** [comment]
:+1:

**Comment by almathew** [comment]
Needs updated in templates

**Comment by aspidites** [comment]
Oh snap. Those indefinite articles, though.

**Comment by galitskyd** [comment]
Ah... I didn't see the file name change :-1:

**Comment by almathew** [comment]
I have no idea what you're talking about.

**Comment by almathew** [comment]
Slightly random question - was this tested using IE in compatibility mode, or an actual copy of IE8?

**Pull request merged**
