### PR TITLE
[PD-3252] Allow for deleting reports.

### PR DESCRIPTION
**Pull request by almathew**
## What's this PR do?
Allows users to delete reports.

This is currently a delete forever action, not an archive. I asked about that in the ticket because it's a bit of a deviation from how we currently do things, but it's also not like we're permanently deleting unrecoverable information.

@aljordan82 I think I addressed your request to use listReports properly?

## Screenshots (if appropriate)
screen shot 2017-10-25 at 2 59 39 pm

## How should this be manually tested?
Make a report.
Delete a report.

### Front-End

- [ ] Works on IE 11 and Edge
- [ ] Works on Mobile
- [ ] Unit tests added or ticket exists to add tests

### Separation of Concerns

- [ ] Back end "business logic" is implemented in plain python, Django model classes, and Django forms. (not Django views or other frameworks)
- [ ] Concerns of UI, api, and model are in separate code units.

### Tests

- [ ] Base classes used for python tests don't do too much unnecessary work.

### CODE REVIEW

**Comment by aljordan82** [comment]
Can the TJD reports be deleted as well?

**Comment by almathew** [comment]
This doesn't add TJD. Just PRM.

**Comment by aljordan82** [comment]
@almathew should TJD be added into this PR? or a new ticket?

**Comment by almathew** [comment]
I will create a new ticket. Now that I know what I'm doing it shouldn't be that hard, but this PR is a complete unit of work, so no reason to stop one just to get the other in.

**Comment by aljordan82** [comment]
Front-end code is fine.

**Comment by tdphillips** [comment]
If you're going to tack your work onto someone else's, you should probably tag your commit with your ticket.

**Pull request merged**
