### PR TITLE
Fix numbers [PD-1154]

### PR DESCRIPTION
**Pull request by tdphillips**
I've made the number look like the other number.

All tests pass.

### CODE REVIEW

**Comment by aspidites** [comment]
@tdphillips  did you verify that the number we decided to display matches whatever is showing up in emails?

**Comment by tdphillips** [comment]
Not yet.

**Comment by tdphillips** [comment]
Just checked. The number equals the other number, as it apparently should.

**Comment by tdphillips** [comment]
Except I forgot to push...

**Pull request merged**
