### PR TITLE
[PD-2168] user management - help page

### PR DESCRIPTION
**Pull request by lemniscate613**
Creates another page with helpful PDF and video documentation.

PDFs included in static files. Video embed responsive.

screen shot 2016-02-16 at 9 40 06 am

### CODE REVIEW

**Comment by darrint** [comment]
Can we do this in such a way that we are not checking a megabyte of binaries into our source control?

**Comment by lemniscate613** [comment]
@darrint Good point. @mklauber just put them on cloudfront: https://github.com/DirectEmployers/MyJobs/commit/0c8cbf6a3873fca5ca29ede653cbe7fef81e89b4

**Comment by tdphillips** [comment]
The files are still in the repo.

**Comment by darrint** [comment]
They are still there. We'll need to rewrite history for this one.

**Comment by lemniscate613** [comment]
@tdphillips You're right. It's gone now.

@darrint just helped me travel back through time to rewrite history. I don't even know what's real anymore.

**Pull request merged**
