### PR TITLE
[PD-2352] Changed Data Source to Source

### PR DESCRIPTION
**Pull request by aspidites**
Exactly what it says. This is on the report generation page, not export.

@darrint there are a couple of tickets dedicated to fixing export names (column and values). For columns, what's the best place to change that? For values, I think you mentioned needing to come up with some other way to handle that, like some kind of format parameter or something.

### CODE REVIEW

**Comment by darrint** [comment]
1. We need to officially decide that "Alias" in ColumnConfiguration is where the export display names go.
2. We need to plumb that name through to the export options api and download views.
3. Update all the ColumnConfiguration entries in setup.py to have names similar to the old system.

**Comment by haliscooper** [comment]
Yes

**Comment by aspidites** [comment]
@darrint 

1 & 2. I think it's safe to say that belongs in a separate ticket then (not that you would disagree, I'm just going on record and saying that because of this, I shouldn't be concerned with export display names here.
3. I can probably work on PD-2349 then. Sounds like export names, due to 1 and 2 would be tackled separately.

Is the above an accurate assessment about what I should be/am able to work on?

**Comment by darrint** [comment]
@aspidites Yes.

**Pull request merged**
