### PR TITLE
Sendgrid to celery [PD-1009]

### PR DESCRIPTION
**Pull request by almathew**
I think I got it all.

Requires `SENDGRID_BATCH_POST_USER` and `SENDGRID_BATCH_POST_PASSWORD` in secrets.py. Both are strings. I don't really care what you make the strings.

All tests pass.

### CODE REVIEW

**Comment by tdphillips** [comment]
Regarding `SENDGRID_BATCH_POST_USER` and `SENDGRID_BATCH_POST_PASSWORD`:

If you change them from what SendGrid currently uses, be sure to also change them on SendGrid. That likely won't be immediately important as I'm betting event posting will still be off when this is deployed, but it should be rectified soon after.

**Comment by almathew** [comment]
@tdphillips I've shared what should be there with @mklauber as well. I think the only time it's really important is when deploying.

**Comment by aspidites** [comment]
@almathew what remains for this to be considered ready to merge?

**Comment by almathew** [comment]
Deployment issues.

**Pull request merged**
