### PR TITLE
Use PRM styles with old apps (homepage, myprofiles, mysearches)

### PR DESCRIPTION
**Pull request by galitskyd**
This is an attempt to unify secure.my.jobs styles and to give the older apps some :heart:

Also fixed the homepage that had a few issues with style and alignment issues.

## Homepage -- Logged Out
screen shot 2015-10-23 at 9 11 49 am

screen shot 2015-10-23 at 9 11 55 am

## Homepage -- Logged In
screen shot 2015-10-23 at 9 12 32 am

screen shot 2015-10-23 at 9 12 52 am

## MyProfiles
screen shot 2015-10-23 at 9 23 53 am

screen shot 2015-10-23 at 9 24 07 am

## MySearches
screen shot 2015-10-23 at 9 24 42 am

screen shot 2015-10-23 at 9 24 50 am

## MySearches -- View Feed (affects PRM as well)
screen shot 2015-10-23 at 9 25 09 am

screen shot 2015-10-23 at 9 25 18 am

### CODE REVIEW

**Comment by lemniscate613** [comment]
Nice! I like your card design and using it throughout... I also like having the menu buttons aligned like that in the Logged In section.

:thumbsup:

**Comment by tdphillips** [comment]
It never struck me until now how unpleasant that striping is.

:+1:

**Comment by fezick** [comment]
I'm all for this.

**Comment by aspidites** [comment]
- The placeholder text feels redundant
- No hover when viewing a saved search, despite there being distinct urls for each job listing

That said, I don't think I'd hold this PR back based on that commentary, and would rather like an improvement ticket to address those points. This is very....very nice all around. Mobile/Tablet is lacking, but that's already been the case and not something introduced by this PR. :100: x :+1:

**Pull request merged**
