### PR TITLE
Modify nuo backend to support assessment [PD-3488]

### PR DESCRIPTION
**Pull request by tdphillips**
## What's this PR do?
More flag shenanigans
## Screenshots (if appropriate)
2017-07-17-082631_663x847_scrot
## Any background context you want to provide?
The score field will need to be updated with the star widget eventually. Our remote form library turned it into a text input as well.

### CODE REVIEW

**Comment by koonsies** [comment]
Do we want this pointed to QC, rather than the partner-reviews branch? I may have missed some conversation.

**Comment by tdphillips** [comment]
No. I thought it was pointed at partner-reviews. Fixed.

**Comment by koonsies** [comment]
For the NUO backend changes, when we get the field for score, the field.widget is returned as "textarea". I haven't looked into it yet, but I'm assuming that's a value returned from Django? To prevent hacky stuff as seen below, we'd need that widget type to be something unique to star.. Like... widget=StarWidget or something.

https://github.com/DirectEmployers/MyJobs/pull/3273/files#diff-3a8871df0b15f4586a16f51a0e06af7aR38

**Comment by tdphillips** [comment]
It's the default widget for an int field.

I made it a radio button locally. As we don't currently have one, that means I get to create my own React radio button widget.

**Comment by koonsies** [comment]
Ivan already created the widget itself. He simply needs the field.widget value to be returned as something that signifies which widget to use.

**Comment by tdphillips** [comment]
We're using django-remote-forms to pass this form from Django land to React land. The widget name we're passing around is an actual Django thing. I guess I can make a dummy Django widget that's basically a copy of Radio.

**Comment by koonsies** [comment]
That's pretty much what I mean. As it stands, the React code checks the widget name to determine what to display.

**Comment by tdphillips** [comment]
Sorry, I modified my comment. Cloning Django's radio input doesn't work.

**Comment by tdphillips** [comment]
Let's start over. This is going to require "hacky stuff" no matter where we do it. The question is where it's going to happen.

**Comment by tdphillips** [comment]
We now pass "StarWidget". It's not going to display in the ui until @iartemiev's code is modified as well.

**Comment by iartemiev** [comment]
Got it, I'll modify momentarily

**Comment by tdphillips** [comment]
I also made it a radio select. I don't know if that matters for the React widget at all.

**Comment by iartemiev** [comment]
Changes made. Works now

**Comment by iartemiev** [comment]
Just tested it and it's not... It's returning `null` again...

**Comment by iartemiev** [comment]
Every other form field has a label... Why can't this?

**Comment by tdphillips** [comment]
Great question. It was a decision by the Django devs.

**Comment by iartemiev** [comment]
Gotcha. That prop is how we set the label that's adjacent to the input in the form. So we need to figure out some kind of workaround then.

Currently, it looks like this:

image

**Comment by tdphillips** [comment]
Any more feedback? Merging this would make other PRs look nicer.

**Comment by iartemiev** [comment]
None from me. Everything seems to be working well now

**Pull request merged**
