### PR TITLE
Registration templates

### PR DESCRIPTION
**Pull request by almathew**
All tests pass. 

Done on top of my other branch because of changes to registration urls and view.

### CODE REVIEW

**Comment by aspidites** [comment]
Looks good. Can't personally test locally.

**Comment by galitskyd** [comment]
Conflicts

**Comment by almathew** [comment]
Lame conflicts. I didn't even have to do any work.

**Comment by aspidites** [comment]
Failed tests. Duplicate transactions, I think.

**Comment by almathew** [comment]
Tests pass

**Comment by aspidites** [comment]
So did you basically just change the base branch you were working on and re-open?

**Comment by almathew** [comment]
No. I added some clearfixes and created a header div with some styling. Network sites have those by default, non-network do not.

**Pull request merged**
