### PR TITLE
Update about page for network sites. PD-1272

### PR DESCRIPTION
**Pull request by fezick**
Updates the about page copy to reflect the job seeker focus of the My.jobs Network. This includes the removal of the testimonial pages and all embedded video.

This is a sister PR to @tdphillips changes that allow for 404 and redirects on /about/ for non-network sites (#1455).

### CODE REVIEW

**Comment by tdphillips** [comment]
dseo_urls.py also has an entry for about/testimonials.

**Comment by fezick** [comment]
Closing to fix merge conflicts and yank testimonial view.

**Comment by fezick** [comment]
Should be good to go now.

**Comment by fezick** [comment]
Merging QC into my branch added a lot of secure redirect items to the urls.py file. @tdphillips, can you make sure this is correct?

**Comment by tdphillips** [comment]
Merging reverted all of my changes to dseo_urls.py.

**Pull request closed without merging**
