### PR TITLE
Add regenerate [PD-2332]

### PR DESCRIPTION
**Pull request by tdphillips**

### CODE REVIEW

**Comment by tdphillips** [comment]
There's no in

**Comment by tdphillips** [comment]
There's no indicator that things happened outside of the popup dismissing.

**Comment by aspidites** [comment]
Depending on which definition of refresh you use (old reporting has been told to do one or the other at different times during development), regenerate may or may not be functioning as intended. If You create a contact report, then retcon a new contact and refresh that report, the counts are the same as the old report, but creating a new contact report shows the new counts.

Example: I started with 162 rows. I added a new record for a new  contact and refreshed the report. Still showed 162 rows. Creating a new contact record with the same parameters showed 163 rows.

**Comment by tdphillips** [comment]
Looking at DynamicReport.regenerate

**Comment by haliscooper** [comment]
It should have the newer data.

**Comment by tdphillips** [comment]
It's magical what saving a modified object will do.

**Pull request merged**
