### PR TITLE
Pd 3452 my.jobs upgrade to webpack3

### PR DESCRIPTION
**Pull request by aljordan82**
## What's this PR do?
Upgrade to webpack 3
## How should this be manually tested?
The production bundles should be minified.

### CODE REVIEW

**Comment by tdphillips** [comment]
What guidance is being requested?

**Comment by aljordan82** [comment]
I am not sure if I am missing anything with this upgrade.
@darrint DO you spot anything wrong with this PR?

**Comment by koonsies** [comment]
What are the thoughts on the speed of webpack 3? If it's prohibitively slow, this update may not be worth it.

**Comment by aljordan82** [comment]
@koonsies It's slightly slower, but I think will need this upgrade eventually.

**Comment by koonsies** [comment]
I'm noticing that as well. Simple changes seem to recompile pretty quickly. I also agree that staying current on our libraries is the way to go.. Just wanted to touch base about speed and see what you thought.

**Pull request merged**
