### PR TITLE
[PD-2846] add remove all button to tags widget

### PR DESCRIPTION
**Pull request by mwarnsleyDE**
## What's this PR do?
This PR adds a remove all button to the tags widget inside of NUO

## Screenshots (if appropriate)
N/A

## Where should the reviewer start?
Start inside of NUO and go to create a partner or edit an existing partner or contact. You can start with the section that says tags and click on it to bring up the tags widget

## How should this be manually tested?
Pull down the repository and go to the NUO application. Partners and Contacts will have a tag section when filling in information to pull up the tags widget. If you hit the select all button for the tags and pull the box back up you will see that there is a remove all button for removing all of the tags. If you click the button it will put the tags back inside of the box and remove them all.

## Any background context you want to provide?
Might need assistance from Jonathan or anyone else if there are suggestions for making the remove all button functionality different

### CODE REVIEW

**Comment by mwarnsleyDE** [comment]
@koonsies maybe some advice or suggestions on this if you want to make it better or different. It will remove all of them but the button will only show if all of the tags are selected so I didn't know if you wanted to change that to a certain amount or anything but just let me know your feedback on this

**Comment by koonsies** [comment]
I am failing to get this button to appear at the moment. It seems that all of the controls disappear when there are a large number of tags selected. I also noticed another issue with tags that we'll discuss on Monday

**Comment by tdphillips** [comment]
Did this ever get discussed?

**Comment by mwarnsleyDE** [comment]
I know I talked to Jonathan a little about it but I don't think we came to a conclusion on it or anything. The buttons go away if they are all selected and you have to click on it again to bring them back and it was like that before, however, the select all button is still implemented so I don't know if Jonathan wants to merge this one and then do a separate one for the button disappearing or if he wants to keep it all in this PR. @koonsies thoughts?

**Pull request merged**
