### PR TITLE
Changed Radio logic to select logic and adjusted JS to match.

### PR DESCRIPTION
**Pull request by misterjonscott**
# Changes

This is a slight change to an already merged PR, to change the radio selects to a select input.

# Notes

There may be a better way to make this element render as a select, but I wasn't able to figure it out and wanted to get this finished by EOD.

### CODE REVIEW

**Comment by lemniscate613** [comment]
Looking at this now...

**Comment by tdphillips** [comment]
https://github.com/DirectEmployers/MyJobs/blob/PD-2108/static/postajob.173-18.js#L97

This is hiding the entire form now.

**Comment by tdphillips** [comment]
The version of that javascript file wasn't updated.

**Comment by lemniscate613** [comment]
:+1: 

I can merge this once @tdphillips confirms it's not flashing for him any more ( @misterjonscott thinks it might be a settings isssue...?).

**Pull request merged**
