### PR TITLE
Dashboard guard against corrupt data

### PR DESCRIPTION
**Pull request by aljordan82**
## What's this PR do?
This should not happen through the dashboard UI but you can actually save anything through the API valid JSON or not, this change converts malformed params or grid data to empty `{}`. 

### Front-End

- [ ] Works on IE 11 and Edge
- [ ] Works on Mobile
- [ ] Unit tests added or ticket exists to add tests

### CODE REVIEW

**Comment by aljordan82** [comment]
DNM until `PD-3568_dashboard-feature-branch` is merged

**Comment by tdphillips** [comment]
If this is a dashboard PR, why is it not pointing at the feature branch?

**Comment by aljordan82** [comment]
@tdphillips I thought the Dashboard branch will be merged by now.

**Comment by vigowei** [comment]
@aljordan82 looks like there is a small conflict and you probably want to improve parsing like we talked about earlier. We can re-open when it's ready again.

**Pull request closed without merging**
