### PR TITLE
PD-3444 - create testing for category reducer

### PR DESCRIPTION
**Pull request by iartemiev**
## What's this PR do?
Test for `cbo/categoryReducer`

## Where should the reviewer start?
`gulp/src/cbo/spec/categoryReducer-spec.js`

## How should this be manually tested?
run test

### CODE REVIEW

**Comment by mwarnsleyDE** [comment]
@aljordan82 can we get a second opinion on this one so we can get it merged

**Comment by aljordan82** [comment]
Can you move this file into a `cbo/reducers/spec/`

**Comment by iartemiev** [comment]
@aljordan82, sure thing. I'll move it shortly

**Comment by iartemiev** [comment]
@aljordan82, I moved the file as requested. Please review

**Pull request merged**
