### PR TITLE
[PD-2333] Report Clone

### PR DESCRIPTION
**Pull request by darrint**
## Review

* `myreports/datasources/base.py` defines a new method for filling out a previously used filter with UI data needed to display it.
* other files in `myreports/datasources` fill out that method on existing datasources.
* UI code uses the state portion of browser history to retrieve/store the prefilled filter. (Redux will improve this in the future but we might still use the history mechanism this way.)
* The two pane select control in reporting needed some adjustments.
* I'm still staying clear of date controls.

## Testing

* Set some filters and run a report.
* Navigate somewhere else.
* Click the menu on the previously run report and choose clone.

### CODE REVIEW

**Comment by aspidites** [comment]
Cloned reports should have a name of "Clone of <name of cloned report>". See old reporting, for example.

**Comment by darrint** [comment]
Fixed. Not sure why I didn't get an Eslint warning on that though. :-/

**Comment by tdphillips** [comment]
Maybe I'm blind but I'm not seeing where the report name is being modified.

**Comment by darrint** [comment]
`ReportList.jsx`

**Pull request merged**
