### PR TITLE
Use local states json file

### PR DESCRIPTION
**Pull request by tdphillips**
This file is both in the local repo and on s3, adding pointless network time which can fail.

### CODE REVIEW

**Comment by aspidites** [comment]
True. Any reason to not just use the bidict you made for postajob? (optionally relocating it to somewhere more appropriate). 

For the record, I meant to do so forever ago, but ended up having to do too many other things and abandoned my efforts (dynamic region/country selection in all PRM forms, IIRC).

**Comment by tdphillips** [comment]
It should basically be a drop-in replacement after confirming that there aren't extra elements in one list vs the other.

I'm writing Selenium tests now, which is the only reason I didn't do that. The remote file seems to be inaccessible from home so I needed some form of workaround.

**Comment by tdphillips** [comment]
You know what, we have a bit of technical debt. I'll work on reducing it by getting rid of one of these.

**Comment by tdphillips** [comment]
Ignore that - there are a few differences that I'm not comfortable with.

Example:
location_data.py, ASM (American Samoa) is a country
usa_regions.json, AS (American Samoa) is a part of the US

**Pull request merged**
