### PR TITLE
Add subject and body to mailto links <PD-1494>

### PR DESCRIPTION
**Pull request by tdphillips**
Tests pass.

### CODE REVIEW

**Comment by tdphillips** [comment]
Tested this locally with settings pointed to production. I checked out one of DE's jobs (the only ones I knew of featuring mailto), clicked apply, and Gmail opened with the correct pre-filled fields.

**Comment by aspidites** [comment]
Works fine, though I have a question: I thought view sources were numeric? When I run this locally, I get "View Source: Dot Jobs". Is that right?

**Comment by tdphillips** [comment]
Interesting question. The thing I call a view source is called "view_source_id" by others. If you look in the seo ViewSource table, it's not even an id. What you're seeing as "Dot Jobs" is the view source with an id of 88 and a name of "Dot Jobs"

**Comment by tdphillips** [comment]
"Dot Jobs" should be more meaningful to the recipient (and probably more understandable to the sender) than 88 would be.

**Comment by tdphillips** [comment]
http://ec2-54-172-15-197.compute-1.amazonaws.com/jenkins/job/MyJobs-Single-Test/79/console

**Comment by aspidites** [comment]
I agree. I just didn't know view sources had a name. :+1: all around, then.

**Pull request merged**
