### PR TITLE
[ST-1254] Location slug properly removed

### PR DESCRIPTION
**Pull request by aspidites**
- I don't know enough about this application to know what else needs to be fixed
- @almathew the test that I added is insufficient. I don't know what parameters I need to pass to reproduce what happens in production, but what is being done certainly isn't it.

### CODE REVIEW

**Comment by aspidites** [comment]
@almathew  I don't know what to do about that error either.

**Comment by almathew** [comment]
For some reason the location breadbox isn't showing up in situations where it should be. Best guess is that you're popping off too much of the location breadcrumb, but that's really just a guess.

I'll try to take a look at it, although I probably won't get a good chance to until tomorrow afternoon.

**Comment by tdphillips** [comment]
Running it locally, the following is what appeared in the rendered page.

`"loc_up_bread_box" href="indiana/usa//indianapolis/indiana/usa/jobs/?P=%22%3E%3Cscript%3E120341734"`

**Comment by almathew** [comment]
Ah, the dreaded //. Good catch Troy.

**Comment by tdphillips** [comment]
Not just //. I was just about to edit my comment. Expected:

`"loc_up_bread_box" href="/indiana/usa/jobs/?P=%22%3E%3Cscript%3E120341734"`

**Comment by aspidites** [comment]
Oh, I see. I declare the breadcrumb code voodoo.

**Pull request closed without merging**
